// renders the parsed groups into the emoji-groups.gen.ts module source

const hexLineOf = (slug: string, codePoints: number[]) => {
  const hex = codePoints
    .toSorted((a, b) => a - b)
    .map((codePoint) => `0x${codePoint.toString(16).toUpperCase()}`)
    .join(', ')

  return `  '${slug}': [${hex}],`
}

export const renderEmojiGroups = (groups: Map<number, string>, version: string) => {
  const slugs = [...new Set(groups.values())].toSorted((a, b) => (a < b ? -1 : 1))

  const lines = slugs.map((slug) => {
    const codePoints = [...groups]
      .filter(([, group]) => group === slug)
      .map(([codePoint]) => codePoint)
    return hexLineOf(slug, codePoints)
  })

  return [
    `// GENERATED by scripts/gen-emoji-groups.ts from Unicode emoji-test.txt ${version}.`,
    '// Run scripts/gen-emoji-groups.ts to regenerate. Do not edit by hand.',
    `export const EMOJI_VERSION = '${version}'`,
    '',
    'export const EMOJI_GROUPS = {',
    ...lines,
    '} as const satisfies Record<string, number[]>',
    '',
  ].join('\n')
}
